// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protoc-27.2-win64/envelope.proto
// Protobuf Java Version: 4.27.2

package com.test.grpc;

public final class EnvelopeProto {
  private EnvelopeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      EnvelopeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_Envelope_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_Envelope_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n protoc-27.2-win64/envelope.proto\022\tmess" +
      "aging\"q\n\010Envelope\022\022\n\nmessage_id\030\001 \001(\t\022\021\n" +
      "\ttimestamp\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\017\n\007payloa" +
      "d\030\004 \001(\014\022\017\n\007version\030\005 \001(\t\022\016\n\006source\030\006 \001(\t" +
      "\"5\n\007Request\022\023\n\013filter_type\030\001 \001(\t\022\025\n\rsour" +
      "ce_filter\030\002 \001(\t\"+\n\010Response\022\016\n\006status\030\001 " +
      "\001(\t\022\017\n\007message\030\002 \001(\t2\213\001\n\017EnvelopeService" +
      "\0229\n\013SendMessage\022\023.messaging.Envelope\032\023.m" +
      "essaging.Response\"\000\022=\n\016StreamMessages\022\022." +
      "messaging.Request\032\023.messaging.Envelope\"\000" +
      "0\001B \n\rcom.test.grpcB\rEnvelopeProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messaging_Envelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messaging_Envelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messaging_Envelope_descriptor,
        new java.lang.String[] { "MessageId", "Timestamp", "Type", "Payload", "Version", "Source", });
    internal_static_messaging_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messaging_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messaging_Request_descriptor,
        new java.lang.String[] { "FilterType", "SourceFilter", });
    internal_static_messaging_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_messaging_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messaging_Response_descriptor,
        new java.lang.String[] { "Status", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
