// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protoc-27.2-win64/envelope.proto
// Protobuf Java Version: 4.27.2

package com.test.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filter_type = 1;</code>
   * @return The filterType.
   */
  java.lang.String getFilterType();
  /**
   * <code>string filter_type = 1;</code>
   * @return The bytes for filterType.
   */
  com.google.protobuf.ByteString
      getFilterTypeBytes();

  /**
   * <code>string source_filter = 2;</code>
   * @return The sourceFilter.
   */
  java.lang.String getSourceFilter();
  /**
   * <code>string source_filter = 2;</code>
   * @return The bytes for sourceFilter.
   */
  com.google.protobuf.ByteString
      getSourceFilterBytes();
}
